version: '3.3'

services:
  demoapi:
    container_name: demoapi_container
    image: demoapi
    ports:
        - 5000:80
        - 5001:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
  clientApp:
    container_name: clientapp
    image: clientapp
    ports:
      - 4200:80
